#!/usr/bin/env bash

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

if [[ "$machine" = "Mac" ]];then
    python3 "$HOME"/.attendance/attendance.py >/tmp/stdout.log 2>/tmp/stderr.log
else
    python3 /opt/attendance/attendance.py &> /opt/attendance/attendance.log

fi
